GUI: EditBox Class Reference
EditBox Class Reference
EditBox widget. You can type into it.
#include <EditBox.h>
Inherits Widget.
Public Member Functions
EditBox (GUISystem *guiSystem, int x, int y, int w, int h)
virtual ~EditBox ()
void render (Renderer *renderer)
void keyChar (int unichar)
void keyDown (int keyCode)
void setMultiline ()
void setText (const std::string &text)
std::string getText ()
Public Member Functions inherited from Widget
Widget ()
Widget (int x, int y, int w, int h)
virtual ~Widget ()
virtual void mouseMove (int x, int y)
virtual void stateChange (State state)
virtual void focusIn ()
virtual void focusOut ()
void addChild (Widget *widget)
void removeChild (Widget *widget)
void setParent (Widget *widget)
void resize (int x, int y, int w, int h)
void updateAbs ()
void setVisibility (bool visible)
bool contain (int posX, int posY)
bool isFocused ()
State getState ()
Public Member Functions inherited from EventEmitter
EventEmitter ()
virtual ~EventEmitter ()
void setQueue (AddToQueue addFunction)
Assings addToQueue function so the events can be sent to the queue.
EventListener::Id addEventListener (EventType eventType, EventListener::Function listenerFunc)
Adds an event listener.
void removeEventListener (EventListener::Id listenerId)
Removes an event listener.
void emitEvent (Event event)
Emitts an event.
Protected Attributes
Color textColor
Color frameColor
Color backgroundColor
Color cursorColor
int backspaceCode
Protected Attributes inherited from Widget
int x
int y
int w
int h
int xAbs
int yAbs
int state
bool focused
bool visible
GUISystem * guiSystem
Private Member Functions
void updateScrollbars ()
void getCursorXY (Renderer *renderer, int &cursorX, int &cursorY)
void findCursorLine ()
void countLines ()
Private Attributes
Handle< Scrollbar > hScrollbar
Handle< Scrollbar > vScrollbar
std::string text
unsigned int cursorPos
unsigned int cursorLine
int lines
float lineHeight
bool multiline
bool hScroll
bool vScroll
Friends
class GUISystem
Additional Inherited Members
Public Types inherited from Widget
enum states { STATE_HOVER, STATE_DOWN, STATE_UP }
typedef char State
Public Types inherited from EventEmitter
typedef std::multimap< EventType, EventListener > Map
Detailed Description
EditBox widget. You can type into it.
Definition at line 16 of file EditBox.h.
Constructor & Destructor Documentation
EditBox()
EditBox::EditBox (GUISystem * guiSystem, int x, int y, int w, int h)
Definition at line 6 of file EditBox.cpp.
References hScrollbar, and vScrollbar.
~EditBox()
EditBox::~EditBox () virtual
Definition at line 26 of file EditBox.cpp.
Member Function Documentation
countLines()
void EditBox::countLines () private
Definition at line 173 of file EditBox.cpp.
References lines, and text.
findCursorLine()
void EditBox::findCursorLine () private
Definition at line 162 of file EditBox.cpp.
References cursorLine, cursorPos, and text.
getCursorXY()
void EditBox::getCursorXY (Renderer * renderer, int & cursorX, int & cursorY) private
Definition at line 142 of file EditBox.cpp.
References cursorLine, cursorPos, Renderer::getTextWidth(), lineHeight, and text.
getText()
std::string EditBox::getText ()
Definition at line 115 of file EditBox.cpp.
References text.
keyChar()
void EditBox::keyChar (int unichar) virtual
Reimplemented from Widget.
Definition at line 57 of file EditBox.cpp.
References countLines(), cursorPos, findCursorLine(), text, and updateScrollbars().
keyDown()
void EditBox::keyDown (int keyCode) virtual
Reimplemented from Widget.
Definition at line 74 of file EditBox.cpp.
References countLines(), cursorPos, findCursorLine(), KEY_BACKSPACE, KEY_ENTER, KEY_LEFT, KEY_RIGHT, multiline, text, and updateScrollbars().
render()
void EditBox::render (Renderer * renderer) virtual
Reimplemented from Widget.
Definition at line 31 of file EditBox.cpp.
References backgroundColor, cursorColor, Renderer::drawFilledRect(), Renderer::drawLine(), Renderer::drawMultilineText(), Renderer::drawRect(), Widget::focused, frameColor, getCursorXY(), Renderer::getLineHeight(), Widget::h, lineHeight, lines, Renderer::setTarget(), text, textColor, vScrollbar, Widget::w, Widget::x, Widget::xAbs, Widget::y, and Widget::yAbs.
setMultiline()
void EditBox::setMultiline ()
Definition at line 104 of file EditBox.cpp.
References multiline.
setText()
void EditBox::setText (const std::string & text)
Definition at line 109 of file EditBox.cpp.
References countLines(), and text.
updateScrollbars()
void EditBox::updateScrollbars () private
Definition at line 120 of file EditBox.cpp.
References Widget::h, lineHeight, lines, vScroll, and vScrollbar.
Friends And Related Function Documentation
GUISystem
friend class GUISystem friend
Definition at line 56 of file EditBox.h.
Member Data Documentation
backgroundColor
Color EditBox::backgroundColor protected
Definition at line 33 of file EditBox.h.
backspaceCode
int EditBox::backspaceCode protected
Definition at line 36 of file EditBox.h.
cursorColor
Color EditBox::cursorColor protected
Definition at line 34 of file EditBox.h.
cursorLine
unsigned int EditBox::cursorLine private
Definition at line 49 of file EditBox.h.
cursorPos
unsigned int EditBox::cursorPos private
Definition at line 48 of file EditBox.h.
frameColor
Color EditBox::frameColor protected
Definition at line 32 of file EditBox.h.
hScroll
bool EditBox::hScroll private
Definition at line 53 of file EditBox.h.
hScrollbar
Handle<Scrollbar> EditBox::hScrollbar private
Definition at line 44 of file EditBox.h.
lineHeight
float EditBox::lineHeight private
Definition at line 51 of file EditBox.h.
lines
int EditBox::lines private
Definition at line 50 of file EditBox.h.
multiline
bool EditBox::multiline private
Definition at line 52 of file EditBox.h.
text
std::string EditBox::text private
Definition at line 47 of file EditBox.h.
textColor
Color EditBox::textColor protected
Definition at line 31 of file EditBox.h.
vScroll
bool EditBox::vScroll private
Definition at line 54 of file EditBox.h.
vScrollbar
Handle<Scrollbar> EditBox::vScrollbar private
Definition at line 45 of file EditBox.h.
The documentation for this class was generated from the following files:
EditBox.h
EditBox.cpp