GUI: App Class Reference
App Class Reference
Application's main class.
#include <App.h>
Public Member Functions
App (int argc, char **argv)
Constructor. Parses command-line arguments.
virtual ~App ()
void initAllegro ()
Initalizes Allegro5 library.
void init ()
Initializes interface and sets the gui.
bool loop (bool waitForEvent=false)
Application's main loop.
void setButtonOnClick (Event &event)
Widget * createWidget (GUISystem *guiSystem)
Private Attributes
ALLEGRO_DISPLAY * display
ALLEGRO_EVENT_QUEUE * queue
ALLEGRO_FONT * font
GUISystem * guiSystem
Renderer * renderer
Handle< EditBox > editBox
Handle< TextField > textField
Handle< Button > setButton
Handle< EditBox > multilineEdit
Handle< Widget > customWidget
Static Private Attributes
static bool initialized = false
Used for preventing multiple instances.
Detailed Description
Application's main class.
Definition at line 26 of file App.h.
Constructor & Destructor Documentation
App()
App::App (int argc, char ** argv)
Constructor. Parses command-line arguments.
Parameters
argc Argument count
argv Argument vector
Definition at line 17 of file App.cpp.
References initialized.
~App()
App::~App () virtual
Definition at line 27 of file App.cpp.
References display, and queue.
Member Function Documentation
createWidget()
Widget * App::createWidget (GUISystem * guiSystem)
Definition at line 156 of file App.cpp.
References gui::Renderer::color(), gui::Button::downStateColor, gui::GUISystem::getRenderer(), gui::Button::hoverStateColor, renderer, gui::Button::setText(), gui::Button::textColor, and gui::Button::upStateColor.
init()
void App::init ()
Initializes interface and sets the gui.
Definition at line 55 of file App.cpp.
References gui::GUISystem::addButton(), gui::GUISystem::addEditBox(), gui::EventEmitter::addEventListener(), gui::GUISystem::addTextField(), gui::GUISystem::addWidget(), createWidget(), customWidget, display, editBox, font, guiSystem, multilineEdit, queue, renderer, gui::Renderer::setBuffer(), setButton, setButtonOnClick(), gui::Renderer::setFont(), gui::GUISystem::setRenderer(), and textField.
initAllegro()
void App::initAllegro ()
Initalizes Allegro5 library.
Definition at line 35 of file App.cpp.
loop()
bool App::loop (bool waitForEvent = false)
Application's main loop.
Parameters
waitForEvent If true, blocks the application until an Allegro's event come.
Returns
Has the application finished.
Definition at line 92 of file App.cpp.
References guiSystem, gui::GUISystem::handleEvents(), gui::GUISystem::keyChar(), gui::GUISystem::keyDown(), gui::GUISystem::mouseButtonDown(), gui::GUISystem::mouseButtonUp(), gui::GUISystem::mouseMove(), queue, and gui::GUISystem::render().
setButtonOnClick()
void App::setButtonOnClick (Event & event)
Definition at line 150 of file App.cpp.
References editBox, gui::EditBox::getText(), gui::TextField::setText(), and textField.
Member Data Documentation
customWidget
Handle<Widget> App::customWidget private
Definition at line 77 of file App.h.
display
ALLEGRO_DISPLAY* App::display private
Definition at line 65 of file App.h.
editBox
Handle<EditBox> App::editBox private
Definition at line 73 of file App.h.
font
ALLEGRO_FONT* App::font private
Definition at line 67 of file App.h.
guiSystem
GUISystem* App::guiSystem private
Definition at line 69 of file App.h.
initialized
bool App::initialized = false static private
Used for preventing multiple instances.
Definition at line 82 of file App.h.
multilineEdit
Handle<EditBox> App::multilineEdit private
Definition at line 76 of file App.h.
queue
ALLEGRO_EVENT_QUEUE* App::queue private
Definition at line 66 of file App.h.
renderer
Renderer* App::renderer private
Definition at line 70 of file App.h.
setButton
Handle<Button> App::setButton private
Definition at line 75 of file App.h.
textField
Handle<TextField> App::textField private
Definition at line 74 of file App.h.
The documentation for this class was generated from the following files:
App.h
App.cpp