GUI: Button Class Reference
Button Class Reference
Button widget. That rectangular thing with inscription on it.
#include <Button.h>
Inherits Widget.
Inherited by CustomWidget.
Public Member Functions
Button ()
Button (GUISystem *guiSystem, int x, int y, int w, int h, std::string text)
virtual ~Button ()
virtual void render (Renderer *renderer)
void stateChange (Widget::State state)
void setText (const std::string &text)
Public Member Functions inherited from Widget
Widget ()
Widget (int x, int y, int w, int h)
virtual ~Widget ()
virtual void keyChar (int uchar)
virtual void keyDown (int keyCode)
virtual void mouseMove (int x, int y)
virtual void focusIn ()
virtual void focusOut ()
void addChild (Widget *widget)
void removeChild (Widget *widget)
void setParent (Widget *widget)
void resize (int x, int y, int w, int h)
void updateAbs ()
void setVisibility (bool visible)
bool contain (int posX, int posY)
bool isFocused ()
State getState ()
Public Member Functions inherited from EventEmitter
EventEmitter ()
virtual ~EventEmitter ()
void setQueue (AddToQueue addFunction)
Assings addToQueue function so the events can be sent to the queue.
EventListener::Id addEventListener (EventType eventType, EventListener::Function listenerFunc)
Adds an event listener.
void removeEventListener (EventListener::Id listenerId)
Removes an event listener.
void emitEvent (Event event)
Emitts an event.
Public Attributes
Color upStateColor
Color hoverStateColor
Color downStateColor
Color textColor
Private Attributes
std::string text
Additional Inherited Members
Public Types inherited from Widget
enum states { STATE_HOVER, STATE_DOWN, STATE_UP }
typedef char State
Public Types inherited from EventEmitter
typedef std::multimap< EventType, EventListener > Map
Protected Attributes inherited from Widget
int x
int y
int w
int h
int xAbs
int yAbs
int state
bool focused
bool visible
GUISystem * guiSystem
Detailed Description
Button widget. That rectangular thing with inscription on it.
Definition at line 13 of file Button.h.
Constructor & Destructor Documentation
Button() [1/2]
Button::Button ()
Definition at line 5 of file Button.cpp.
Button() [2/2]
Button::Button (GUISystem * guiSystem, int x, int y, int w, int h, std::string text)
Definition at line 10 of file Button.cpp.
References Widget::guiSystem.
~Button()
Button::~Button () virtual
Definition at line 17 of file Button.cpp.
Member Function Documentation
render()
void Button::render (Renderer * renderer) virtual
Reimplemented from Widget.
Definition at line 22 of file Button.cpp.
References downStateColor, Renderer::drawFilledRect(), Renderer::drawText(), Widget::h, hoverStateColor, Renderer::setTarget(), Widget::state, Widget::STATE_DOWN, Widget::STATE_HOVER, Widget::STATE_UP, text, textColor, upStateColor, Widget::w, Widget::x, Widget::xAbs, Widget::y, and Widget::yAbs.
setText()
void Button::setText (const std::string & text)
Definition at line 57 of file Button.cpp.
References text.
stateChange()
void Button::stateChange (Widget::State state) virtual
Reimplemented from Widget.
Definition at line 37 of file Button.cpp.
References GUISystem::createEvent(), EventEmitter::emitEvent(), Widget::guiSystem, MOUSE_BUTTON_DOWN, MOUSE_BUTTON_UP, Widget::state, Widget::STATE_DOWN, Widget::STATE_HOVER, and Widget::STATE_UP.
Member Data Documentation
downStateColor
Color Button::downStateColor
Definition at line 26 of file Button.h.
hoverStateColor
Color Button::hoverStateColor
Definition at line 25 of file Button.h.
text
std::string Button::text private
Definition at line 32 of file Button.h.
textColor
Color Button::textColor
Definition at line 27 of file Button.h.
upStateColor
Color Button::upStateColor
Definition at line 24 of file Button.h.
The documentation for this class was generated from the following files:
Button.h
Button.cpp