GUI: CustomWidget Class Reference
CustomWidget Class Reference
Test class for adding own widgets mechanism.
#include <CustomWidget.h>
Inherits gui::Button.
Public Member Functions
CustomWidget (GUISystem *guiSystem, int x, int y)
void onClick (Event &event)
Public Member Functions inherited from gui::Button
Button (GUISystem *guiSystem, int x, int y, int w, int h, std::string text)
virtual ~Button ()
virtual void render (Renderer *renderer)
void stateChange (Widget::State state)
void setText (const std::string &text)
Public Member Functions inherited from gui::Widget
Widget ()
Widget (int x, int y, int w, int h)
virtual ~Widget ()
virtual void keyChar (int uchar)
virtual void keyDown (int keyCode)
virtual void mouseMove (int x, int y)
virtual void focusIn ()
virtual void focusOut ()
void addChild (Widget *widget)
void removeChild (Widget *widget)
void setParent (Widget *widget)
void resize (int x, int y, int w, int h)
void updateAbs ()
void setVisibility (bool visible)
bool contain (int posX, int posY)
bool isFocused ()
State getState ()
Public Member Functions inherited from gui::EventEmitter
EventEmitter ()
virtual ~EventEmitter ()
void setQueue (AddToQueue addFunction)
Assigns addToQueue function so the events can be sent to the queue.
EventListener::Id addEventListener (EventType eventType, EventListener::Function listenerFunc)
Adds an event listener.
void removeEventListener (EventListener::Id listenerId)
Removes an event listener.
void emitEvent (Event &event)
Emits an event.
Additional Inherited Members
Public Types inherited from gui::Widget
enum states { STATE_HOVER, STATE_DOWN, STATE_UP }
typedef char State
Public Types inherited from gui::EventEmitter
typedef std::multimap< EventType, EventListener > Map
Public Attributes inherited from gui::Button
Color upStateColor
Color hoverStateColor
Color downStateColor
Color textColor
Protected Attributes inherited from gui::Widget
int x
int y
int w
int h
int xAbs
int yAbs
int state
bool focused
bool visible
Protected Attributes inherited from gui::EventEmitter
GUISystem * guiSystem
Detailed Description
Test class for adding own widgets mechanism.
Definition at line 22 of file CustomWidget.h.
Constructor & Destructor Documentation
CustomWidget()
CustomWidget::CustomWidget (GUISystem * guiSystem, int x, int y)
Definition at line 12 of file CustomWidget.cpp.
References gui::EventEmitter::addEventListener(), and onClick().
Member Function Documentation
onClick()
void CustomWidget::onClick (Event & event)
Definition at line 18 of file CustomWidget.cpp.
References gui::GUISystem::createEvent(), gui::EventEmitter::guiSystem, and gui::Button::setText().
The documentation for this class was generated from the following files:
CustomWidget.h
CustomWidget.cpp