GUI: gui::Scrollbar Class Reference
gui::Scrollbar Class Reference
Scrollbar widget. Has a bar and it scrolls!
#include <Scrollbar.h>
Inherits gui::Widget.
Public Member Functions
Scrollbar (GUISystem *guiSystem, int x, int y, int w, int h)
virtual ~Scrollbar ()
void render (Renderer *renderer)
void downButtonClick (Event &event)
void upButtonClick (Event &event)
void sliderMouseDown (Event &event)
void sliderMouseUp (Event &event)
void sliderMouseMove (Event &event)
void setSlider (float position)
void setSliderLength (float length)
float getSliderPosition ()
Public Member Functions inherited from gui::Widget
Widget ()
Widget (int x, int y, int w, int h)
virtual ~Widget ()
virtual void keyChar (int uchar)
virtual void keyDown (int keyCode)
virtual void mouseMove (int x, int y)
virtual void stateChange (State state)
virtual void focusIn ()
virtual void focusOut ()
void addChild (Widget *widget)
void removeChild (Widget *widget)
void setParent (Widget *widget)
void resize (int x, int y, int w, int h)
void updateAbs ()
void setVisibility (bool visible)
bool contain (int posX, int posY)
bool isFocused ()
State getState ()
Public Member Functions inherited from gui::EventEmitter
EventEmitter ()
virtual ~EventEmitter ()
void setQueue (AddToQueue addFunction)
Assigns addToQueue function so the events can be sent to the queue.
EventListener::Id addEventListener (EventType eventType, EventListener::Function listenerFunc)
Adds an event listener.
void removeEventListener (EventListener::Id listenerId)
Removes an event listener.
void emitEvent (Event &event)
Emits an event.
Protected Attributes
Color backgroundColor
Color frameColor
Protected Attributes inherited from gui::Widget
int x
int y
int w
int h
int xAbs
int yAbs
int state
bool focused
bool visible
Protected Attributes inherited from gui::EventEmitter
GUISystem * guiSystem
Private Attributes
Handle< Button > upButton
Handle< Button > downButton
Handle< Button > slideButton
EventListener::Id mouseMoveListenerId
float sliderPosition
float sliderLength
int holdPointX
int holdPointY
float sliderPrevPos
Friends
class GUISystem
Additional Inherited Members
Public Types inherited from gui::Widget
enum states { STATE_HOVER, STATE_DOWN, STATE_UP }
typedef char State
Public Types inherited from gui::EventEmitter
typedef std::multimap< EventType, EventListener > Map
Detailed Description
Scrollbar widget. Has a bar and it scrolls!
Definition at line 22 of file Scrollbar.h.
Constructor & Destructor Documentation
Scrollbar()
Scrollbar::Scrollbar (GUISystem * guiSystem, int x, int y, int w, int h)
Definition at line 13 of file Scrollbar.cpp.
References gui::EventEmitter::addEventListener(), downButton, downButtonClick(), gui::MOUSE_BUTTON_DOWN, gui::MOUSE_BUTTON_UP, gui::Widget::setParent(), setSlider(), slideButton, sliderMouseDown(), sliderMouseUp(), sliderPosition, upButton, and upButtonClick().
~Scrollbar()
virtual gui::Scrollbar::~Scrollbar () inline virtual
Definition at line 26 of file Scrollbar.h.
References downButtonClick(), render(), setSlider(), setSliderLength(), sliderMouseDown(), sliderMouseMove(), sliderMouseUp(), and upButtonClick().
Member Function Documentation
downButtonClick()
void Scrollbar::downButtonClick (Event & event)
Definition at line 50 of file Scrollbar.cpp.
References setSlider(), and sliderPosition.
getSliderPosition()
float gui::Scrollbar::getSliderPosition () inline
Definition at line 38 of file Scrollbar.h.
References sliderPosition.
render()
void Scrollbar::render (Renderer * renderer) virtual
Reimplemented from gui::Widget.
Definition at line 41 of file Scrollbar.cpp.
References backgroundColor, gui::Renderer::drawFilledRect(), gui::Renderer::drawRect(), frameColor, gui::Widget::h, gui::Renderer::setTarget(), gui::Widget::w, gui::Widget::x, gui::Widget::xAbs, gui::Widget::y, and gui::Widget::yAbs.
setSlider()
void Scrollbar::setSlider (float position)
Definition at line 105 of file Scrollbar.cpp.
References gui::Widget::h, gui::Widget::resize(), slideButton, sliderLength, sliderPosition, gui::Widget::w, and gui::Widget::y.
setSliderLength()
void Scrollbar::setSliderLength (float length)
Definition at line 114 of file Scrollbar.cpp.
References setSlider(), sliderLength, and sliderPosition.
sliderMouseDown()
void Scrollbar::sliderMouseDown (Event & event)
Definition at line 60 of file Scrollbar.cpp.
References gui::EventEmitter::addEventListener(), gui::Event::getEventObject(), gui::Event::getType(), holdPointX, holdPointY, gui::MOUSE_BUTTON_DOWN, gui::MOUSE_MOVE, mouseMoveListenerId, slideButton, sliderMouseMove(), sliderPosition, and sliderPrevPos.
sliderMouseMove()
void Scrollbar::sliderMouseMove (Event & event)
Definition at line 90 of file Scrollbar.cpp.
References gui::Event::getEventObject(), gui::Event::getType(), gui::Widget::h, holdPointY, gui::MOUSE_MOVE, setSlider(), sliderLength, sliderPrevPos, and gui::Widget::y.
sliderMouseUp()
void Scrollbar::sliderMouseUp (Event & event)
Definition at line 78 of file Scrollbar.cpp.
References gui::Event::getType(), gui::MOUSE_BUTTON_UP, mouseMoveListenerId, gui::EventEmitter::removeEventListener(), and slideButton.
upButtonClick()
void Scrollbar::upButtonClick (Event & event)
Definition at line 55 of file Scrollbar.cpp.
References setSlider(), and sliderPosition.
Friends And Related Function Documentation
GUISystem
friend class GUISystem friend
Definition at line 57 of file Scrollbar.h.
Member Data Documentation
backgroundColor
Color gui::Scrollbar::backgroundColor protected
Definition at line 41 of file Scrollbar.h.
downButton
Handle<Button> gui::Scrollbar::downButton private
Definition at line 46 of file Scrollbar.h.
frameColor
Color gui::Scrollbar::frameColor protected
Definition at line 42 of file Scrollbar.h.
holdPointX
int gui::Scrollbar::holdPointX private
Definition at line 53 of file Scrollbar.h.
holdPointY
int gui::Scrollbar::holdPointY private
Definition at line 54 of file Scrollbar.h.
mouseMoveListenerId
EventListener::Id gui::Scrollbar::mouseMoveListenerId private
Definition at line 49 of file Scrollbar.h.
slideButton
Handle<Button> gui::Scrollbar::slideButton private
Definition at line 47 of file Scrollbar.h.
sliderLength
float gui::Scrollbar::sliderLength private
Definition at line 52 of file Scrollbar.h.
sliderPosition
float gui::Scrollbar::sliderPosition private
Definition at line 51 of file Scrollbar.h.
sliderPrevPos
float gui::Scrollbar::sliderPrevPos private
Definition at line 55 of file Scrollbar.h.
upButton
Handle<Button> gui::Scrollbar::upButton private
Definition at line 45 of file Scrollbar.h.
The documentation for this class was generated from the following files:
Scrollbar.h
Scrollbar.cpp